"""upgrading foundation models for cms system

Revision ID: f219a1032e96
Revises: 06e786c326c8
Create Date: 2025-12-19 20:17:30.531750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f219a1032e96'
down_revision: Union[str, Sequence[str], None] = '06e786c326c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.add_column('post_tags', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('post_tags_tags_id_fkey'), 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'])
    op.drop_column('post_tags', 'tags_id')
    op.add_column('tags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.add_column('post_tags', sa.Column('tags_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key(op.f('post_tags_tags_id_fkey'), 'post_tags', 'tags', ['tags_id'], ['id'])
    op.drop_column('post_tags', 'tag_id')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
